sudo: true
language: node_js
node_js:
  - "6"
branches:
  only: 
    - feature/travis
    - master
addons:
  sauce_connect:
    username: dkushner
    access_key:
      secure: "aLWsECUkiUA1xzoOaC9mCAOPp8TDJtl1rxixW8fE+6ynrbFiG76HXXTnLGkBvnJHJ6LQ2gEjBGrHgYp6WCqQ3VffMP3ala6UvUn9AsPXn6bmm9yn6fg0xZKgX0z88InlLj0pWHfMp3MDK3INTxNHflv/Fz9hp66pe0LUq6rD1eYG+PxvB6pWrpbYUr3jQ/8Z7RjETB58MjKwld+AgiG9SxVde0OoqG4TTwKoLvOZg+IYWhm7J1LDKKgGO7hQmGjLamOPt5RDu65n6iCz4C6JjbrVvuEP54s1kupNQABCTh9hP9gTKjGeHwHZBDUR1SulLX8Gz6tVM5bTTrG6Oh1DT9waqshvMFHoXNH/SmZvHI57b46JKRtqhSANCa6Awp83rd7JMzbGt+7X3IucCAxlbO5FrREuNYfxky0R+O78cL0i08jqG8IsMA5pbxj9r4hbdJZqO0QEniT+ykpI/NemmOFqsRP3VpVKAeSMb9Nn0Aon7b5GJQyRorH7xRQIn43GQ46IPmGtu4kiTFUlyCQb4N9o5bnDggwY2n3bWjt+BIkf0rbtd0MWK86XndqvcaizamYax08Eiw79VWbb9dQ+8R6/OWAtvin3RpUVTDbBTOVqaEb3n9qq7RU7WEHLffOoUr4SbGzda7iThkv/I2LbvCOpOol3JKuQ2qAKG3MtEKs="
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
deploy:
  provider: npm
  email: root@davidkushner.me
  api_key:
    secure: Pc2rhGVBHHdXHqHHcMoZbtTanQxhNozR5KcZ7X8V1/Xo1ytGM3+95yP4rxvPaAu+gzaNMH0dYvvJUkG/hDlFJ8eFuYjH2ged/Ju5n8KuUmNPPwS8VIB1NC7AuZCjRlqCYSARlAmdFlil655A1ERycA4ydNbpo1IEJ5FFJC2jaQiMZpfwy08bv2JmlHYrBn62Z3W9hMOXdx6pfbOQ/WSyq7Ldljjo/sOOeqJfgKeC4mHtrGefaN0sRvO6XajT73Ztr2g0iFrQ30SkhkQ/dmEweRz/VxpcCt+qqQf+QaOU6VU3xYwYksPGkfol2oo9K7es1p7Q/zs4QlNHnVgQZ7iRA2er4spMwAjy21HaXpYK0GUu1Cjbr9QWydX3b1JtUU+CS1Fja95gSsPRwF0ojvwy3q9UY1rlyi8ptZRBe+u05eRVAa/7JsKzgHZlivlCgyK02xuSDxJairjlMwb0z0f8YzHFEH+rg0TZMQcD/PrkcJnzMceEDP4EC78gYJfS+d82El4CqFQSFC05mkEblwy6DtQXlCpEXfvbIVJPj6S8NMXW96nnB3cc2aD9m7moS49ZT7gOV+9W5bO9/DOxbO/VKC4pycwIOmtOrSh32r4aGtPQ2Y9hHFZlhTm5jssX2mMEJISh4OoFA+82VFU6dwj9ua6KBrY4gL6ShF7X9rNFD5I=
  on:
    tags: true
    repo: dkushner/ergjs
